name: CI-Build

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true    
  workflow_dispatch:    # 加入這行來允許手動觸發

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-CI-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-CI-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          customImage: unityci/editor:ubuntu-2022.3.6f1-windows-mono-3.0.1
          # Optional: specify output path
          # outputPath: build 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-StandaloneWindows64 # Artifact name
          path: build/StandaloneWindows64 # Path to the build output
